services:
  invox-transcribe:
    build:
      context: ../invox-transcribe
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - transcribe_logs:/app/logs
      - transcribe_models:/app/models
    restart: unless-stopped
    networks:
      - transcribe
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.docker.compose.service=transcription"
      - "com.docker.compose.project=invox"

networks:
  transcribe:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16

volumes:
  transcribe_logs:
    driver: local
  transcribe_models:
    driver: local
