services:
  # frontend:
  #   build:
  #     context: ../possum-client
  #     dockerfile: Dockerfile
  #     target: development
  #   volumes:
  #     - ../possum-client:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend
  #     - frontend

  # backend:
  #   build:
  #     context: ../possum-backend
  #     dockerfile: Dockerfile
  #     target: npm_dev_install
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../possum-backend:/usr/src/app
  #     - ../possum-backend/src/data:/usr/src/app/dist/data:ro
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - .env
  #   command: npm run start:dev
  #   depends_on:
  #     - db
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #   networks:
  #     - backend
  #     - frontend

  # db:
  #   image: postgres:17-alpine
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_DB=${POSSUM_DB_NAME}
  #     - POSTGRES_USER=${POSSUM_DB_USER}
  #     - POSTGRES_PASSWORD=${POSSUM_DB_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes/database:/var/lib/postgresql/data
  #   networks:
  #     - backend

  # webserver:
  #   image: nginx:1-alpine
  #   ports:
  #     - "4200:4200"
  #   restart: always
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./config/webserver/nginx/templates/server-variables.conf.template:/etc/nginx/templates/server-variables.conf.template:ro
  #     - ./config/webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   cap_add:
  #     - NET_ADMIN

  invox-transcribe:
    build:
      context: ../invox-transcribe
    ports:
      - "9000:9000"
    # networks:
    #   - backend


# networks:
#   frontend:
#     driver: bridge
#     driver_opts:
#       com.docker.network.enable_ipv6: "true"
#   backend:
#     name: backend
#     internal: true